version: "3.8"
services:
  test-data:
    image: vetcal.azurecr.io/vetcal-test-data
    build: ./testData
    container_name: vetcal-test-data
    depends_on:
      - hapi
  hapi:
    image: hapiproject/hapi:latest
    ports:
      - "8080:8080"
    container_name: hapi
    configs:
      - source: hapi
        target: /app/config/application.yaml
  vetcal:
    image: vetcal.azurecr.io/vetcal-fe
    build: ./vet-cal
    ports:
      - "80:80"
    container_name: vetcal-fe
    depends_on:
      - hapi
      - test-data
configs:
  hapi:
    file: ./hapi.application.yaml
