version: "3"
services:
  test-data:
    build: ./testData
    #depends_on:
     # - hapi
    container_name: test-data
  hapi:
    image: hapiproject/hapi:latest
    ports:
      - "8080:8080" 
    container_name: hapi 